
[[features]]
name = "accounts"
csdl_files = [
    "AccountService_v1.xml",
    "ManagerAccountCollection_v1.xml",
    "ManagerAccount_v1.xml",
    "Privileges_v1.xml",
]
patterns = [
    "AccountService.*",
    "ManagerAccountCollection.*",
    "ManagerAccount.*",
]

[[features]]
name = "assembly"
csdl_files = [
    "Assembly_v1.xml",
]
patterns = [
    "Assembly.*",
    "Assembly.*.*",
]

[[features]]
name = "bios"
csdl_files = [
    "Bios_v1.xml",
]
patterns = [
    "Bios.*",
]

[[features]]
name = "boot_options"
csdl_files = [
    "BootOption_v1.xml",
    "BootOptionCollection_v1.xml",
]
patterns = [
    "BootOption.*",
    "BootOptionCollection.*",
]

[[features]]
name = "chassis"
csdl_files = [
    "Chassis_v1.xml",
    "ChassisCollection_v1.xml",
    "Circuit_v1.xml",
    "CircuitCollection_v1.xml",
    "PhysicalContext_v1.xml",
    "Redundancy_v1.xml",
    "SoftwareInventory_v1.xml",
]
patterns = [
    "ChassisCollection.*",
    "Chassis.*",
    "PhysicalContext.*",
]

[[features]]
name = "ethernet-interfaces"
csdl_files = [
    "EthernetInterfaceCollection_v1.xml",
    "EthernetInterface_v1.xml",
    "VLanNetworkInterface_v1.xml",
    "IPAddresses_v1.xml"
]
patterns = [
    "EthernetInterfaceCollection.*",
    "EthernetInterface.*"
]

[[features]]
name = "memory"
csdl_files = [
    "Memory_v1.xml",
    "MemoryCollection_v1.xml",
    "MemoryMetrics_v1.xml",
]
patterns = [
    "Memory.*",
    "MemoryCollection.*",
    "MemoryMetrics.*",
]

[[features]]
name = "network-adapters"
csdl_files = [
    "NetworkAdapterCollection_v1.xml",
    "NetworkAdapter_v1.xml"
]
patterns = [
    "NetworkAdapterCollection.*",
    "NetworkAdapter.*"
]

[[features]]
name = "computer-systems"
csdl_files = [
    "ComputerSystem_v1.xml",
    "ComputerSystemCollection_v1.xml",
    "PhysicalContext_v1.xml",
    "Redundancy_v1.xml",
    "ResourceBlock_v1.xml",
    "ResourceBlockCollection_v1.xml",
    "SoftwareInventory_v1.xml",
]
patterns = [
    "ComputerSystem.*",
    "ComputerSystemCollection.*",
    "PhysicalContext.*",
]

[[features]]
name = "update-service"
csdl_files = [
    "UpdateService_v1.xml",
    "SoftwareInventory_v1.xml",
    "SoftwareInventoryCollection_v1.xml",
    "Key_v1.xml",
    "PhysicalContext_v1.xml",
]
patterns = [
    "UpdateService.*",
    "SoftwareInventory.*",
    "SoftwareInventoryCollection.*",
]

[[features]]
name = "log-services"
csdl_files = [
    "LogService_v1.xml",
    "LogServiceCollection_v1.xml",
    "LogEntry_v1.xml",
    "LogEntryCollection_v1.xml",
    "Event_v1.xml",
]
patterns = [
    "LogService.*",
    "LogServiceCollection.*",
    "LogEntry.*",
    "LogEntryCollection.*",
    "Event.*.*"
]
root_patterns = [ "Event.v1_0_0.Event" ]

[[features]]
name = "managers"
csdl_files = [
    "Manager_v1.xml",
    "ManagerCollection_v1.xml",
    "SoftwareInventory_v1.xml",
]
patterns = [
    "Manager.*",
    "ManagerCollection.*",
]

[[features]]
name = "pcie-devices"
csdl_files = [
    "PCIeDevice_v1.xml",
    "PCIeDeviceCollection_v1.xml",
]
patterns = [
    "PCIeDevice.*",
    "PCIeDeviceCollection.*",
]

[[features]]
name = "processors"
csdl_files = [
    "Processor_v1.xml",
    "ProcessorCollection_v1.xml",
    "ProcessorMetrics_v1.xml",
]
patterns = [
    "Processor.*",
    "ProcessorCollection.*",
    "ProcessorMetrics.*",
]

[[features]]
name = "power"
csdl_files = [
    "Power_v1.xml",
    "PowerSubsystem_v1.xml",
]
patterns = [
    "Power.*",
    "Power.*.*",
    "PowerSubsystem.*",
]

[[features]]
name = "power-supplies"
csdl_files = [
    "PowerSupply_v1.xml",
    "PowerSupplyCollection_v1.xml",
    "PowerSupplyMetrics_v1.xml",
]
patterns = [
    "PowerSupply.*",
    "PowerSupplyCollection.*",
    "PowerSupplyMetrics.*",
]

[[features]]
name = "sensors"
csdl_files = [
    "Fan_v1.xml",
    "FanCollection_v1.xml",
    "Sensor_v1.xml",
    "SensorCollection_v1.xml",
    "EnvironmentMetrics_v1.xml",
]
patterns = [
    "Sensor.*",
    "SensorCollection.*",
    "Fan.*",
    "FanCollection.*",
    "EnvironmentMetrics.*",
]

[[features]]
name = "storages"
csdl_files = [
    "Drive_v1.xml",
    "DriveCollection_v1.xml",
    "DriveMetrics_v1.xml",
    "PCIeDevice_v1.xml",
    "PCIeDeviceCollection_v1.xml",
    "Protocol_v1.xml",
    "SoftwareInventory_v1.xml",
    "Storage_v1.xml",
    "StorageCollection_v1.xml",
    "StorageController_v1.xml",
    "StorageControllerMetrics_v1.xml",
    "Volume_v1.xml",
    "VolumeCollection_v1.xml",
]
swordfish_csdl_files = [
    "Capacity_v1.xml",
    "DataStorageLoSCapabilities_v1.xml",
    "IOStatistics_v1.xml",
    "StorageReplicaInfo_v1.xml",
]
patterns = [
    "Storage.*",
    "StorageCollection.*",
    "StorageController.*",
    "StorageControllerMetrics.*",
    "Volume.*",
    "VolumeCollection.*",
    "Drive.*",
    "DriveCollection.*",
    "DriveMetrics.*",
]


[[features]]
name = "secure-boot"
csdl_files = [
     "SecureBoot_v1.xml"
]
patterns = [
     "SecureBoot.*"
]

[[features]]
name = "thermal"
csdl_files = [
    "LeakDetection_v1.xml",
    "LeakDetector_v1.xml",
    "LeakDetectorCollection_v1.xml",
    "Thermal_v1.xml",
    "ThermalMetrics_v1.xml",
    "ThermalSubsystem_v1.xml",
]
patterns = [
    "LeakDetection.*",
    "LeakDetector.*",
    "LeakDetectorCollection.*",
    "Thermal.*",
    "Thermal.*.*",
    "ThermalMetrics.*",
    "ThermalSubsystem.*",
    "ThermalSubsystem.*.*",
]

[[oem-features]]
vendor = "nvidia-bluefield"
name = "computer-systems"
oem_csdl_files = [ # files must be located in {workspace-root}/oem/{vendor}/...
    "NvidiaComputerSystem_v1.xml",
]
csdl_files = []

[[oem-features]]
vendor = "nvidia-baseboard"
name = "chassis"
oem_csdl_files = [ # files must be located in {workspace-root}/oem/{vendor}/...
    "NvidiaChassis_v1.xml",
]
csdl_files = []
