
[[features]]
name = "accounts"
csdl_files = [
    "AccountService_v1.xml",
    "ManagerAccountCollection_v1.xml",
    "ManagerAccount_v1.xml",
    "Privileges_v1.xml"
]
patterns = [
    "AccountService.*",
    "ManagerAccountCollection.*",
    "ManagerAccount.*"
]

[[features]]
name = "events"
csdl_files = [
    "EventService_v1.xml",
    "Event_v1.xml",
    "EventDestination_v1.xml",
]
patterns = [
    "EventService.*",
]

[[oem-features]]
vendor = "lenovo"
name = "accounts"
oem_csdl_files = [ # files must be located in {workspace-root}/oem/{vendor}/...
    "LenovoAccountService_v1.xml",
]
csdl_files = []
